# Generated by Django 3.0.5 on 2020-05-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choosing', '0004_delete_user'),
        ('user', '0002_auto_20200513_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='voted',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='choosing.Candidate'),
        ),
    ]
