# Generated by Django 3.0.5 on 2020-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
