# Generated by Django 3.0.5 on 2020-05-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_is_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_voted',
        ),
        migrations.RemoveField(
            model_name='account',
            name='voted',
        ),
    ]
