# Generated by Django 3.0.5 on 2020-05-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200513_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
