# Generated by Django 3.0.5 on 2020-05-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choosing', '0003_auto_20200513_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
